apiVersion: v1
kind: Service
metadata:
   name: redis
   labels:
        app: redis-service
        version: v1
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
