apiVersion: v1
kind: Service
metadata:
   name: voting-svc
   labels:
        app: voting-app
        version: v1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30012
  selector:
    app: voting-app
