apiVersion: v1
kind: ReplicationController
metadata:
  name: httpbin-rc
spec:
  selector:
      app: httpbin
  replicas: 3
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - image: kennethreitz/httpbin
        name: httpbin-container
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ip
            port: 80
