apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-apache-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-apache
  template:
    metadata:
      labels:
        app: frontend-apache
    spec:
      containers:
      - image: rohitkandiyal/nginx_dynamic:1.0
        name: nginx-dynamic-container
        args:
        - ApaChe
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /dynamic
            port: 80
