apiVersion: constraints.gatekeeper.sh/v1beta1
kind: CheckReviewObj
metadata:
  name: check-rev-obj
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "test-gatekeeper"
