apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-dep
  labels:
    app: result-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      labels:
        app: result-app
        version: v1
    spec:
      containers:
      - image: kodekloud/examplevotingapp_result:v1
        name: result-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
