apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-dep
  labels:
    app: voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      labels:
        app: voting-app
        version: v1
    spec:
      containers:
      - image: kodekloud/examplevotingapp_vote:v1
        name: voting-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
