apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-dep
  labels:
    app: worker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
        version: v1
    spec:
      containers:
      - image: kodekloud/examplevotingapp_worker
        name: worker-app
        imagePullPolicy: IfNotPresent
