apiVersion: v1
kind: Service
metadata:
  name: httpbin-svc
  namespace: httpbin
spec:
  ports:
  - port: 8085
    protocol: TCP
    targetPort: 80
  selector:
    app: httpbin
  sessionAffinity: None
  type: ClusterIP
